apiVersion: v1
kind: Service
metadata:
  name: vproapp-service
spec:
  ports:
  - port: {{ .Values.app.port }}
    protocol: TCP
    targetPort: {{ .Values.app.port }}
  selector:
    app: {{ .Values.app.name }}
  type: ClusterIP