apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.memcached.name }}
  labels:
    app: {{ .Values.memcached.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.memcached.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.memcached.name }}
    spec:
      containers:
      - name: {{ .Values.memcached.name }}
        image: {{ .Values.memcached.image }}:{{ .Values.memcached.tag }}
        ports:
        - name: vpromc-port
          containerPort: {{ .Values.memcached.port }}