apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  ports:
  - port: {{ .Values.memcached.port }}
    targetPort: vpromc-port
    protocol: TCP
  selector:
    app: {{ .Values.memcached.name }}
  type: ClusterIP