apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.name }}
spec:
  ports:
  - port: {{ .Values.rabbitmq.port }}
    targetPort: vpromq01-port
    protocol: TCP
  selector:
    app: {{ .Values.rabbitmq.name }}
  type: ClusterIP